{"name": "Проверка логина c неверным паролем", "status": "passed", "description": "Пытаемся залогиниться в аккаунт пользователя, получаем ошибку 401", "start": 1725567289948, "stop": 1725567290143, "uuid": "f1416e2c-7701-4e57-8bba-ef8e6697f079", "historyId": "0a9292d29b3c8de0dc4c2560bad5138f", "testCaseId": "0a9292d29b3c8de0dc4c2560bad5138f", "fullName": "tests.test_login_user.TestLoginUser#test_no_such_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-R6MANS9"}, {"name": "thread", "value": "42268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}